site_name: 运维知识体系
nav:
- 主页: index.md
- 持续集成:
    - Devops: devops/index.md
    - Gitlab: devops/gitlab.md
    - Jenkins: devops/jenkins.md
    - ArgoCD: devops/argocd.md
    - ArgoWorkflows: devops/argoworkflows.md
    - ArgoEvents: devops/argoevents.md
    - ArgoRollouts: devops/argorollouts.md
- Kubernetes:
    - Quick Start: kubernetes/Quick.md
    - Kube-Scheduler: kubernetes/kube-scheduler.md
    - Kube-Controller-Manager: kubernetes/kube-controller-manager.md
    - Kube-Proxy: kubernetes/kube-proxy.md
    - Kubelet: kubernetes/kubelet.md
    - Kube-APIServer: kubernetes/kube-apiserver.md
    - CNI: kubernetes/cni.md
    - CSI: kubernetes/csi.md
    - Ingress:
      - Quick Start: ingress/Quick.md
    - Openkruise:
      - Quick Start: openkruise/Quick.md
- 云原生:
    - 快速开始: user-guide/Quick.md
    - Prometheus:
      - Quick Start: prometheus/Quick.md
    - VictoriaMetrics:
      - Quick Start: victoriametrics/Quick.md
    - Harbor:
      - Quick Start: harbor/Quick.md
    - Istio:
      - Quick Start: istio/Quick.md
    - KubeSphere:
      - Quick Start: kubesphere/Quick.md
- Code:
    - Python: code/python.md
    - Golang:
         - Gin: code/gin.md
         - Kubebuilder: code/kubebuilder.md
    - Shell: code/shell.md
- 博客:
    - Introduction: blog/index.md
- 关于:
    - License: about/license.md
theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  palette:
    scheme: default
    primary: teal
  features:
    - navigation.footer
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss

plugins:
  - social
  - search:
      # lang: zh
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  # - offline:
  #     enabled: !ENV [OFFLINE, false]
  - tags:
      enabled: !ENV [CI, false]
      tags_file: tags.md
      # tags_extra_files:
      #   compatibility.md:
      #     - compat
      #   web.md:
      #     - html
      #     - js
      #     - css
# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true
#       enabled: !ENV [CI, false]
#       type: date
#       fallback_to_build_date: true
#   - git-authors
#   - git-committers:
#       enabled: !ENV [CI, false]
#       repository: kbsonlong/argo
#       branch: main
repo_url: https://github.com/kbsonlong/argo
repo_name: kbsonlong/argo
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
    # default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kbsonlong
    - icon: fontawesome/solid/paper-plane
      link: mailto:kbsonlong@gmail.com
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/alongparty

copyright: Copyright &copy; 2018 - 2023 Martin Donath
